# Generated by Django 4.2.5 on 2025-10-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_backup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='backups_to_keep',
            field=models.IntegerField(default=10),
        ),
    ]
