# Generated by Django 4.2.5 on 2025-10-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_backup', '0002_credentials_backups_to_keep'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
