# Generated by Django 4.2.5 on 2025-10-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_backup', '0003_backup_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='enabled',
        ),
        migrations.AddField(
            model_name='credentials',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
