# Generated by Django 4.2.5 on 2025-10-08 20:04

from django.db import migrations, models
import services.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('db_backup', '0004_remove_backup_enabled_credentials_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='backup_file',
            field=models.FileField(storage=services.storage_backends.PrivateMediaStorage(), upload_to='backups/'),
        ),
    ]
