# Generated by Django 4.0.4 on 2023-08-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
