# Generated by Django 4.2.5 on 2023-09-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_history_sent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackList',
        ),
        migrations.AddField(
            model_name='history',
            name='message',
            field=models.TextField(default=None),
        ),
    ]
