# Generated by Django 4.2.5 on 2023-10-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0003_delete_blacklist_history_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=250)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('use_tls', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-datetime'], 'verbose_name': 'History email', 'verbose_name_plural': 'History emails'},
        ),
        migrations.AddField(
            model_name='user',
            name='email_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactform.emailsender'),
        ),
    ]
