# Generated by Django 4.2.5 on 2023-10-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0004_emailsender_alter_history_options_user_email_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsender',
            name='use_tls',
        ),
        migrations.AddField(
            model_name='emailsender',
            name='use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
