# Generated by Django 4.2.5 on 2025-07-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0007_alter_history_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_spam',
            field=models.BooleanField(default=True),
        ),
    ]
