# Generated by Django 4.2.7 on 2025-04-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='blog/images', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default=None, verbose_name='Descripción corta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.CharField(default=None, help_text='Separadas por comas', max_length=255, verbose_name='Palabras clave'),
            preserve_default=False,
        ),
    ]
