# Generated by Django 4.2.7 on 2025-04-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_image_alter_post_description_alter_post_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
        migrations.AddField(
            model_name='post',
            name='banner_image_url',
            field=models.CharField(blank=True, help_text='URL de la imagen del banner', max_length=255, null=True, verbose_name='Banner URL'),
        ),
    ]
