# Generated by Django 4.2.7 on 2025-06-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_image_options_post_banner_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Ella Skin & Spa Wellness Team', max_length=255, verbose_name='Autor'),
        ),
    ]
