# Generated by Django 4.2.5 on 2025-10-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_related_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('done', 'Listo para publicar'), ('published', 'Publicado')], default='draft', max_length=20, verbose_name='Estado'),
        ),
    ]
