# Generated by Django 4.2.5 on 2025-03-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='odoo_tasks',
            new_name='file_s3_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AddField(
            model_name='video',
            name='odoo_task',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
