# Generated by Django 4.2.5 on 2025-03-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_rename_odoo_tasks_video_file_s3_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file_s3_url',
        ),
        migrations.AddField(
            model_name='video',
            name='tech_context',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
