# Generated by Django 4.2.5 on 2025-03-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_remove_video_file_s3_url_video_tech_context_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='video_drive_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
