# Generated by Django 4.2.5 on 2025-03-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0004_remove_video_video_video_video_drive_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='tech_context',
            new_name='context',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='odoo_task',
            new_name='workflow_link',
        ),
        migrations.AddField(
            model_name='video',
            name='posted_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
