# Generated by Django 4.2.5 on 2025-03-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0005_rename_tech_context_video_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_drive_url',
            field=models.URLField(default='https://www.darideveloper.com'),
            preserve_default=False,
        ),
    ]
