# Generated by Django 4.2.5 on 2025-03-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0006_alter_video_video_drive_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_drive_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='workflow_link',
        ),
        migrations.AddField(
            model_name='video',
            name='video_drive_name',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
