# Generated by Django 4.2.5 on 2025-03-31 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0007_remove_video_tags_remove_video_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='posted_link',
        ),
    ]
