# Generated by Django 4.2.5 on 2024-12-11 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AiModel',
        ),
    ]
