# Generated by Django 4.2.5 on 2024-12-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_alter_user_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
